
export const TIME_TICK = 'TIME_TICK';
export const TICKER_STARTED = 'TICKER_STARTED';
export const CREATE_PARTICLES = 'CREATE_PARTICLES';
export const START_PARTICLES = 'START_PARTICLES';
export const STOP_PARTICLES = 'STOP_PARTICLES';
export const UPDATE_MOUSE_POS = 'UPDATE_MOUSE_POS';
export const RESIZE_WINDOW = 'RESIZE_WINDOW';